name: Checkout, Tag/release, Build, Push
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  build-push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: GitHub Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker metadata
      id: docker_metadatas
      uses: docker/metadata-action@v5
      with:
        images: ${{ vars.DOCKERHUB_USERNAME }}/paper-server
        tags: |
          type=schedule
          type=semver,pattern={{version}}
          type=raw,value=${{ steps.tag_version.outputs.new_tag }}
          type=raw,value=latest
    - name: Create changelog text
      id: changelog
      uses: loopwerk/tag-changelog@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        exclude_types: other
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        push: true
        context: .
        tags: ${{ steps.docker_metadatas.outputs.tags }}
    - name: GH Release
      uses: fregante/release-with-changelog@v3.6.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Commit CHANGELOG.md
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        branch: ${{ github.ref_name }}
        commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: CHANGELOG.md
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ vars.DOCKERHUB_USERNAME }}/paper-server
        short-description: ${{ github.event.repository.description }}
  # reporting:
  #   needs: build-push
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Actions for Discord
  #     env:
  #       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  #     uses: Ilshidur/action-discord@0.3.2
  #     with:
  #       args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been built and pushed.'
    